sudo: required
services:
  - docker
before-install:
  - docker build -t GauravSegan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true GauravSegan/docker-react npm run test -- --coverage
