sudo: required
services:
  - docker
before_install:
  - docker build -t segantravis -f Dockerfile.dev .

script:
  - docker run -e CI=true segantravis npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-420231204725"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: 
    secure: "$aws_access_key"
  secret_access_key:
    secure: "$aws_secret_key"
## here we need to deploy on master branch and not on feature branch

 ## here ebs detects the dockerfile and builds it automatically since we configured EB for docker deployment 
 ## docker build cmd in before_install was for building image for the container in which travis CI had to run the tests and make a build 

  